In [1]:
import numpy as np

In [2]:
#column vector
a = np.array([4,5,6])
print(a.shape)

(3,)


In [3]:
# obtaining a particular entry
print(a[0])

4


In [4]:
# row vector
row = np.array([[4,5,6]])
print(row.shape)

(1, 3)


In [5]:
# obtaining a particular entry
print(row[0,1])

5


In [8]:
# creating a matrix with all zeros
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# creating a matrix with all ones
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# creating a matrix filled with the same constant
c = np.full((3,3),8)
print(c)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [14]:
# creating a matrix with random values
d = np.random.random((3,3))
print(d)

[[0.19754719 0.73082865 0.4474619 ]
 [0.94572871 0.60812358 0.38477156]
 [0.39876752 0.32884584 0.44926134]]


In [26]:
# creating a matrix
A = np.array([[1,2],[3,4],[5,6]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [20]:
A = np.array([1,2,3])
B = np.array([[1,2,3,]])
print('-'*10 + 'A')
print(A)
print(A.shape)
print(type(A))
print('-'*10 + 'B')
print(B)
print(B.shape)
print(type(B))

----------A
[1 2 3]
(3,)
<class 'numpy.ndarray'>
----------B
[[1 2 3]]
(1, 3)
<class 'numpy.ndarray'>


In [21]:
# creating another matrix
B = np.array([[11,12,13,14],[15,16,17,18]])
B

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [23]:
print(B)
print(type(B))

[[11 12 13 14]
 [15 16 17 18]]
<class 'numpy.ndarray'>


In [24]:
# transpose a matrix
B.T

array([[11, 15],
       [12, 16],
       [13, 17],
       [14, 18]])

In [27]:
# matirx-matrix multiplication
np.dot(A,B)

array([[ 41,  44,  47,  50],
       [ 93, 100, 107, 114],
       [145, 156, 167, 178]])

In [28]:
# matrix-matrix multiplication
# size should be matched!
np.dot(B,A)

ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [29]:
# coefficient matrix A nad a vector b
A = np.array([[60,5.5,1],[65,5.0,0],[55,6.0,1]])
b = np.array([66,70,78])

In [33]:
# identity matrix
eye3 = np.eye(3)
eye3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# computing an inverse
from numpy.linalg import inv
A_inv = inv(A)
A_inv

array([[ 0.08695652,  0.00869565, -0.08695652],
       [-1.13043478,  0.08695652,  1.13043478],
       [ 2.        , -1.        , -1.        ]])

In [36]:
# wrong matrix multiplication
A * A_inv

array([[ 5.21739130e+00,  4.78260870e-02, -8.69565217e-02],
       [-7.34782609e+01,  4.34782609e-01,  0.00000000e+00],
       [ 1.10000000e+02, -6.00000000e+00, -1.00000000e+00]])

In [38]:
# correct matrix multiplication
A.dot(A_inv)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 8.8817842e-16,  1.0000000e+00, -8.8817842e-16],
       [-8.8817842e-16,  0.0000000e+00,  1.0000000e+00]])

In [39]:
# solution of a linear system
x = A_inv.dot(b)
x

array([ -0.43478261,  19.65217391, -16.        ])

In [41]:
# A better way to solve the same linear system
from numpy.linalg import solve
x = solve(A,b)
x

array([ -0.43478261,  19.65217391, -16.        ])