In [1]:
import numpy as np

In [2]:
# reshape
test_matrix = [[1,2,3,4],[5,6,7,8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
test_matrix

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [4]:
print(test_matrix)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [5]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [6]:
test = np.array(test_matrix).reshape(8,)

In [7]:
test

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
test.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [9]:
test.reshape(-1.3)

TypeError: 'float' object cannot be interpreted as an integer

In [10]:
test.reshape(-1,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
test.reshape(-2,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
test.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
test.reshape(,2)

SyntaxError: invalid syntax (198331566.py, line 1)

In [14]:
test.reshape(-3,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
np.array(test_matrix).reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
np.array(test_matrix).reshape(2,4).shape

(2, 4)

In [20]:
np.array(test_matrix).reshape(2,-1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
np.array(test_matrix).reshape(2,-1).shape

(2, 4)

In [22]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [23]:
np.array(test_matrix).reshape(2,2,2).shape

(2, 2, 2)

In [25]:
test_matrix = [[[1,2,3,4], [11,12,15,18]], [[21,22,23,24], [31,32,35,38]]]
np.array(test_matrix).flatten()

array([ 1,  2,  3,  4, 11, 12, 15, 18, 21, 22, 23, 24, 31, 32, 35, 38])

In [26]:
test_matrix.shape

AttributeError: 'list' object has no attribute 'shape'

In [28]:
test_matrix

[[[1, 2, 3, 4], [11, 12, 15, 18]], [[21, 22, 23, 24], [31, 32, 35, 38]]]

In [30]:
np.array(test_matrix)

array([[[ 1,  2,  3,  4],
        [11, 12, 15, 18]],

       [[21, 22, 23, 24],
        [31, 32, 35, 38]]])

In [29]:
np.array(test_matrix).shape

(2, 2, 4)

In [31]:
np.array(test_matrix).reshape(4,1,4)

array([[[ 1,  2,  3,  4]],

       [[11, 12, 15, 18]],

       [[21, 22, 23, 24]],

       [[31, 32, 35, 38]]])

In [32]:
np.array(test_matrix).reshape(4,1,4).shape

(4, 1, 4)