In [1]:
import numpy as np

In [2]:
# operation in array
test = np.arange(1,10+1)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
test.sum()

55

In [4]:
test.sum(dtype=np.float)

C:\Users\Huiseop\AppData\Local\Temp\ipykernel_9564\3972869309.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test.sum(dtype=np.float)


55.0

In [5]:
test = np.arange(1,12+1).reshape(3,4)

In [6]:
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
test.sum()

78

In [8]:
test.sum(axis=1)

array([10, 26, 42])

In [9]:
test.sum(axis=0)

array([15, 18, 21, 24])

In [10]:
third_order_tensor = np.array([test,test,test])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [11]:
third_order_tensor.sum(axis=2) #로우, 가로 기준 (!차원)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [12]:
third_order_tensor.sum(axis=1) # 컬럼, 세로 기준 (2차원)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [13]:
third_order_tensor.sum(axis=0) # 깊이 기준 (3차원)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [25]:
for i in range(0,2+1):
    print(f"""
    {i}번재 test 매트릭스의 합입니다. 
    {third_order_tensor.sum(axis=i)}
    """)
    # print(test.sum(axis=i))


    0번재 test 매트릭스의 합입니다. 
    [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
    

    1번재 test 매트릭스의 합입니다. 
    [[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]
    

    2번재 test 매트릭스의 합입니다. 
    [[10 26 42]
 [10 26 42]
 [10 26 42]]
    


In [26]:
test = np.arange(1, 13).reshape(3,4)
test

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
test.mean(), test.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [29]:
test.std(), test.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

In [30]:
np.exp(test), np.sqrt(test)

(array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
        [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
        [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]]),
 array([[1.        , 1.41421356, 1.73205081, 2.        ],
        [2.23606798, 2.44948974, 2.64575131, 2.82842712],
        [3.        , 3.16227766, 3.31662479, 3.46410162]]))

In [31]:
# Concatenate

In [39]:
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.vstack((a,b))
a, b , c, c.shape

(array([1, 2, 3]),
 array([2, 3, 4]),
 array([[1, 2, 3],
        [2, 3, 4]]),
 (2, 3))

In [42]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
c = np.hstack((a,b))
a, b, c, c.shape


(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]),
 (3, 2))

In [43]:
d = np.vstack((a,b))
d, d.shape

(array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]),
 (6, 1))

In [44]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [45]:
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [46]:
np.concatenate((a,b), axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

c= np.concatenate( (a,b.T) ,axis=1)
a, a.shape, b, b.shape, c, c.shape

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 array([[5, 6]]),
 (1, 2),
 array([[1, 2, 5],
        [3, 4, 6]]),
 (2, 3))

In [50]:
d = np.concatenate( (a,b.T) ,axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [52]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[7],[8]])
e = np.concatenate( (a,b), axis=1)
a, a.shape, b, b.shape, e, e.shape

(array([[1, 2],
        [3, 4]]),
 (2, 2),
 array([[7],
        [8]]),
 (2, 1),
 array([[1, 2, 7],
        [3, 4, 8]]),
 (2, 3))

In [53]:
f = np.concatenate((a,b), axis=0)
f, f.shape

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [54]:
f = np.concatenate((a,b))
f, f.shape

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

In [56]:
a.tolist()

[[1, 2], [3, 4]]