In [1]:
# import the numpy module 
import numpy as np

In [4]:
# creating the numpy array
test_array = np.array(['3','7',1,2], float)
test_array

array([3., 7., 1., 2.])

In [5]:
type(test_array[2])

numpy.float64

In [8]:
test_array = np.array(['3','7',1,2], np.float32)
test_array

array([3., 7., 1., 2.], dtype=float32)

In [11]:
print(type(test_array[3]))
print(test_array.dtype)

<class 'numpy.float32'>
float32


In [15]:
print(np.array([[1, 4, 5, "8"]], np.float32).shape)
print(np.array([1,2,3,4]).shape)

(1, 4)
(4,)


In [14]:
test_array.shape

(4,)

In [16]:
# array shape
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [18]:
matrix = [[1,2,3,4],[5,6,7,8],[9,9,9,9,]]
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 9, 9, 9]]

In [21]:
type(matrix)

list

In [22]:
np.array(matrix, int).shape

(3, 4)

In [24]:
matrix = [[1,2,3,4],[5,6,7,8],[9,9,9,9,10]]
np.array(matrix, int).shape # column의 수가 맞지 않음.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [28]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
a = np.array(tensor, float).shape 

In [30]:
type(a)
print(a)

(4, 3, 4)


In [32]:
print(f"depth of tensor is {a[0]} \n column of tensor is {a[1]} \n row of tensor is {a[2]}")

depth of tensor is 4 
 column of tensor is 3 
 row of tensor is 4


In [34]:
np.array(tensor, int).ndim

3

In [36]:
np.array(tensor, int).size

48

In [43]:
# numpy dtype
a = np.array([[1,2,3], [4.5,6,7.8]], dtype=int)

In [44]:
np.array([[1,2,3],[4.5,'5.5','7']], dtype=np.float32)

array([[1. , 2. , 3. ],
       [4.5, 5.5, 7. ]], dtype=float32)

In [46]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
dtype=np.float32).nbytes

24

In [58]:
np.array([[1, 2.7, 3], [5, 3.5, 1]], dtype=np.float32).nbytes

24

In [59]:
np.array([[1, 2, 3], [5, 3, 1]], dtype=int).nbytes

24

In [60]:
np.array([[1, 2, 3], [5, 3, 1]], dtype=float).nbytes

48

In [61]:
np.array([[1, 2, 3], [5, 3, 1]], dtype=np.float128).nbytes

AttributeError: module 'numpy' has no attribute 'float128'

In [62]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.int8).nbytes

6

In [63]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.float64).nbytes

48

In [64]:
np.array([[1, 2, 3], [4.5, "5", "6"]], 
         dtype=np.unit8).nbytes

AttributeError: module 'numpy' has no attribute 'unit8'