In [1]:
import numpy as np

In [4]:
test = np.array([[1,2,3],[4.7,5,6.9]], int)
test

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
test[0][0]

1

In [6]:
test[1][2]

6

In [7]:
test[0][0] = 999
test

array([[999,   2,   3],
       [  4,   5,   6]])

In [8]:
test[0][0] = 254
test

array([[254,   2,   3],
       [  4,   5,   6]])

In [9]:
#Slicing
test = np.array([
    [1,2,3,4], [2,34,57.8,4],[3,4,6,9],[1,5,8,33]
], int)

In [10]:
test

array([[ 1,  2,  3,  4],
       [ 2, 34, 57,  4],
       [ 3,  4,  6,  9],
       [ 1,  5,  8, 33]])

In [11]:
test[:2,:]

array([[ 1,  2,  3,  4],
       [ 2, 34, 57,  4]])

In [12]:
test[:1+1,:]

array([[ 1,  2,  3,  4],
       [ 2, 34, 57,  4]])

In [15]:
test[0:1+1,0:]

array([[ 1,  2,  3,  4],
       [ 2, 34, 57,  4]])

In [17]:
test[2:3+1, 0:1+1]

array([[3, 4],
       [1, 5]])

In [18]:
test = np.array([
    [1,2,3,4,5], [6,7,8,9,10]
], int)
test[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [21]:
test

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
test[1,1:3]

array([7, 8])

In [20]:
test[1:3]

array([[ 6,  7,  8,  9, 10]])

In [22]:
a = np.arange(100).reshape(10,10)

In [23]:
a[:,-1].reshape(-1,1)

array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [24]:
np.arange(40).reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [26]:
np.arange(40).reshape(10,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [27]:
np.arange(0, 5, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [28]:
np.arange(33).reshape(3,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [29]:
#ones, zeros, empty

In [32]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [33]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.zeros(shape=(3,6), dtype=np.float)

C:\Users\Huiseop\AppData\Local\Temp\ipykernel_27380\2936322389.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(shape=(3,6), dtype=np.float)


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [35]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [36]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.empty((6,5))

array([[1.44202104e-311, 9.58487353e-322, 0.00000000e+000,
        0.00000000e+000, 1.42419802e-306],
       [3.16251369e+180, 3.74271162e+233, 2.28176674e+243,
        5.23584369e-143, 2.87287195e+257],
       [2.87518202e+161, 1.05117823e-153, 3.98472821e+252,
        2.44040351e+204, 3.60241447e+252],
       [6.06003397e+233, 2.87244893e+161, 4.03823998e+246,
        7.00699346e-077, 1.16071791e-028],
       [9.06707496e+271, 8.42102838e-143, 5.49419094e-143,
        7.93260771e+223, 2.59027869e-144],
       [2.28895457e+243, 2.22038430e+142, 3.99910946e+252,
        3.19854319e+209, 7.79952704e-143]])

In [40]:
np.empty((33,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [6.95282357e-310, 4.64421707e-322, 1.44218978e-311],
       [1.44218978e-311, 1.44218978e-311, 1.44218978e-311],
       [1.44218978e-311, 1.44218979e-311, 1.44218978e-311],
       [1.44218978e-311, 1.44218978e-311, 1.44218979e-311],
       [1.44218979e-311, 1.44218978e-311, 1.44218978e-311],
       [1.44218978e-311, 1.44218979e-311, 1.44218979e-311],
       [1.44218979e-311, 1.44218979e-311, 1.44218979e-311],
       [1.44218979e-311, 1.44218979e-311, 1.44218979e-311],
       [1.44218979e-311, 1.44218978e-311, 1.44218978e-311],
       [1.44218978e-311, 1.44218978e-311, 1.44218978e-311],
       [1.44218979e-311, 1.44218978e-311, 1.44218978e-311],
       [1.44218984e-311, 1.44218984e-311, 1.44218984e-311],
       [1.44218984e-311, 1.44218984e-311, 1.44218984e-311],
       [1.44218984e-311, 1.44218984e-311, 1.44218984e-311],
       [1.44218984e-311, 1.44218984e-311, 1.44218984e-311],
       [1.44218984e-311, 1.44218984e-311

In [41]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [42]:
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [43]:
np.empty_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [44]:
# eye, identity & digonal

In [46]:
a = np.identity(n=3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
b = np.identity(n=3, dtype=np.int8)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [49]:
c= np.identity(n=3, dtype=np.float64)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
a.dtype, b.dtype, c.dtype

(dtype('float64'), dtype('int8'), dtype('float64'))

In [55]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [56]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [58]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [60]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
np.diag(matrix, k=1)

array([1, 5])

In [62]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.39009247, 0.76759546, 0.32265503, 0.67943645, 0.1608918 ],
       [0.42493941, 0.50873185, 0.83630415, 0.70922583, 0.78160898]])

In [63]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.44987884, 0.78976767, 0.50644468, 0.91171839, 0.09391203],
       [0.19188894, 0.03052276, 0.78209964, 0.44445257, 0.10011761]])

In [64]:
np.random.normal(0,1,10).reshape(2,5)

array([[-0.18014412,  2.26737859, -0.20793613,  0.35943734,  0.8984166 ],
       [-0.87752461,  1.4342155 ,  0.85264831,  0.15795785,  1.15180428]])

In [65]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.15875523,  0.46401677,  0.84019948,  0.99711343,  0.34260063],
       [ 0.06458304,  1.39560617, -2.17593041, -0.75348161,  1.11528438]])